services:
  cloud_messaging:
    build: ./cloud_messaging/.
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Tokyo"

  stun_server:
    build: ./webrtc/server/stun/.
    ports:
      - "3478:3478"

  signaling_server:
    build: ./webrtc/server/signaling/.
    ports:
      - "3000:3000"
    environment:
      TZ: "Asia/Tokyo"

  agora_certification:
    build: ./agora_certification/.
    ports:
      - "8080:8080"

  reminder_cron:
    build: ./reminder_cron/.
    ports:
      - "8080:8080"
